version: '3.1'

services:
  # pgadmin4 for pgbouncer.
  pgadmin4-master:
    image: fenglc/pgadmin4
    ports:
      - 5050:5050
    links:
      - postgres:postgres
    environment:
      DEFAULT_USER: pgbouncer_database
      DEFAULT_PASSWORD: 12345678
  # Postgres database.
  postgres:
    image: postgres:9.6.5 
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432   
    command: postgres -c 'max_connections=10000' -c 'shared_buffers=512MB'
  # Postgres database.
  pgbouncer:
    image: brainsam/pgbouncer:1.7.2
    environment:
      DB_HOST: postgres
      DB_USER: postgres           # define credentials
      DB_PASSWORD: postgres       # define credentials
      DB_port: 5432
      POOL_MODE: transaction
      DEFAULT_POOL_SIZE: 56
      MAX_CLIENT_CONN: 10000
    # volumes:
    #   - ./pgbouncer:/etc/pgbouncer
    links:
      - postgres:postgres
    ports:
      - 6432:6432                 # PgBouncer port
